#!/bin/sh
inkscape -D -z --file=rails/public/chapters/img_javascript/ch1-Z-G-7.svg --export-pdf=rails/public/chapters/img_javascript/ch1-Z-G-7.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-10.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-10.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-11.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-11.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch4-Z-G-3.svg --export-pdf=rails/public/chapters/img_javascript/ch4-Z-G-3.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-52.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-52.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-14.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-14.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3.18.svg --export-pdf=rails/public/chapters/img_javascript/ch3.18.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch1-Z-G-10.svg --export-pdf=rails/public/chapters/img_javascript/ch1-Z-G-10.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-4.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-4.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-19.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-19.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-16.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-16.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-3.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-3.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-23.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-23.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-17.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-17.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-31.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-31.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-21.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-21.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch1-Z-G-6.svg --export-pdf=rails/public/chapters/img_javascript/ch1-Z-G-6.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-6.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-6.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-62.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-62.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-51.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-51.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-16.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-16.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-22.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-22.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-8.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-8.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-11.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-11.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-59.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-59.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-54.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-54.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-5.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-5.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-18.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-18.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-2.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-2.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-12.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-12.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-64.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-64.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-12.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-12.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch1-Z-G-1.svg --export-pdf=rails/public/chapters/img_javascript/ch1-Z-G-1.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-65.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-65.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ex1-14.svg --export-pdf=rails/public/chapters/img_javascript/ex1-14.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-17.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-17.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch1-Z-G-13.svg --export-pdf=rails/public/chapters/img_javascript/ch1-Z-G-13.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-15.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-15.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-63.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-63.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-15.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-15.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-7.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-7.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-6.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-6.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-13.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-13.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-20.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-20.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-13.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-13.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch2-Z-G-37.svg --export-pdf=rails/public/chapters/img_javascript/ch2-Z-G-37.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/ch3-Z-G-9.svg --export-pdf=rails/public/chapters/img_javascript/ch3-Z-G-9.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/Fig3.30.svg --export-pdf=rails/public/chapters/img_original/Fig3.30.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-30.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-30.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch1-Z-G-7.svg --export-pdf=rails/public/chapters/img_original/ch1-Z-G-7.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-52.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-52.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-10.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-10.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-11.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-11.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch4-Z-G-3.svg --export-pdf=rails/public/chapters/img_original/ch4-Z-G-3.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-14.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-14.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-51.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-51.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3.18.svg --export-pdf=rails/public/chapters/img_original/ch3.18.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch1-Z-G-10.svg --export-pdf=rails/public/chapters/img_original/ch1-Z-G-10.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-4.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-4.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-19.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-19.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-16.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-16.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch4-Z-G-1.svg --export-pdf=rails/public/chapters/img_original/ch4-Z-G-1.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-32.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-32.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-3.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-3.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-23.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-23.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-17.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-17.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-31.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-31.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-21.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-21.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-49.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-49.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch1-Z-G-6.svg --export-pdf=rails/public/chapters/img_original/ch1-Z-G-6.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-6.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-6.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-62.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-62.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-35.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-35.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-51.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-51.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-16.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-16.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-58.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-58.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-22.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-22.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-8.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-8.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-11.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-11.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-59.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-59.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-54.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-54.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-53.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-53.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-5.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-5.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-60.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-60.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-18.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-18.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-2.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-2.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-12.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-12.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-64.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-64.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-12.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-12.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch1-Z-G-1.svg --export-pdf=rails/public/chapters/img_original/ch1-Z-G-1.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-27.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-27.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-65.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-65.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-59.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-59.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-17.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-17.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch1-Z-G-13.svg --export-pdf=rails/public/chapters/img_original/ch1-Z-G-13.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-15.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-15.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-63.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-63.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-26.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-26.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-15.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-15.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-66.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-66.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-7.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-7.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-6.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-6.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-25.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-25.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-13.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-13.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-20.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-20.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-67.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-67.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch4-Z-G-2.svg --export-pdf=rails/public/chapters/img_original/ch4-Z-G-2.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-23.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-23.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-53.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-53.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-13.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-13.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-37.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-37.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch2-Z-G-42.svg --export-pdf=rails/public/chapters/img_original/ch2-Z-G-42.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-9.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-9.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/ch3-Z-G-24.svg --export-pdf=rails/public/chapters/img_original/ch3-Z-G-24.svg.pdf

inkscape -D -z --file=rails/public/chapters/img_original/chip.std.svg --export-pdf=rails/public/chapters/img_original/chip.std.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/Fig5.11b.std.svg --export-pdf=rails/public/chapters/img_original/Fig5.11b.std.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/Fig5.14b.std.svg --export-pdf=rails/public/chapters/img_original/Fig5.14b.std.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/Fig5.15c.std.svg --export-pdf=rails/public/chapters/img_original/Fig5.15c.std.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/Fig5.1a.std.svg --export-pdf=rails/public/chapters/img_original/Fig5.1a.std.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/Fig5.2.std.svg --export-pdf=rails/public/chapters/img_original/Fig5.2.std.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/Fig5.4c.std.svg --export-pdf=rails/public/chapters/img_original/Fig5.4c.std.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/Fig5.4c.std.svg --export-pdf=rails/public/chapters/img_javascript/Fig5.4c.std.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/Fig5.5b.std.svg --export-pdf=rails/public/chapters/img_original/Fig5.5b.std.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/Fig5.7b.std.svg --export-pdf=rails/public/chapters/img_original/Fig5.7b.std.svg.pdf

inkscape -D -z --file=rails/public/chapters/img_javascript/Fig5.11b.std.svg --export-pdf=rails/public/chapters/img_javascript/Fig5.11b.std.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/Fig5.14b.std.svg --export-pdf=rails/public/chapters/img_javascript/Fig5.14b.std.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/Fig5.15c.std.svg --export-pdf=rails/public/chapters/img_javascript/Fig5.15c.std.svg.pdf

inkscape -D -z --file=rails/public/chapters/img_original/527table.svg --export-pdf=rails/public/chapters/img_original/527table.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_original/preserving_table.svg --export-pdf=rails/public/chapters/img_original/preserving_table.svg.pdf
inkscape -D -z --file=rails/public/chapters/img_javascript/preserving_table.svg --export-pdf=rails/public/chapters/img_javascript/preserving_table.svg.pdf

inkscape -D -z --file=./rails/public/chapters/img_javascript/Fig4.4a.std.svg --export-pdf=./rails/public/chapters/img_javascript/Fig4.4a.std.svg.pdf
inkscape -D -z --file=./rails/public/chapters/img_javascript/Fig4.5a.std.svg --export-pdf=./rails/public/chapters/img_javascript/Fig4.5a.std.svg.pdf
inkscape -D -z --file=./rails/public/chapters/img_javascript/Fig4.6a.std.svg --export-pdf=./rails/public/chapters/img_javascript/Fig4.6a.std.svg.pdf
inkscape -D -z --file=./rails/public/chapters/img_original/Fig4.4a.std.svg   --export-pdf=./rails/public/chapters/img_original/Fig4.4a.std.svg.pdf
inkscape -D -z --file=./rails/public/chapters/img_original/Fig4.5a.std.svg   --export-pdf=./rails/public/chapters/img_original/Fig4.5a.std.svg.pdf
inkscape -D -z --file=./rails/public/chapters/img_original/Fig4.6a.std.svg   --export-pdf=./rails/public/chapters/img_original/Fig4.6a.std.svg.pdf

