$pdf_mode = 1;
# Index base name must match the root .tex (sicpjs / sicpy / sicp); see
# javascript/editions.ts (SICP_EDITION -> outputBaseName). Default: sicpjs.
my $sicp_edition = lc( ( $ENV{'SICP_EDITION'} // '' ) =~ s/\s//gr );
my $sicp_base =
    $sicp_edition eq 'py'  ? 'sicpy'
  : $sicp_edition eq 'scm' ? 'sicp'
  :                          'sicpjs';
$makeindex = "makeindex -s ../scripts/makeindex.ist -l $sicp_base.idx";
