$pdf_mode = 1;
# Index base name must match the root .tex (sicpjs / sicpy); see
# javascript/editions.ts (SICP_EDITION). Anything but "py" -> sicpjs.
my $sicp_base = ( ( $ENV{'SICP_EDITION'} // '' ) =~ /^\s*py\s*$/i ) ? 'sicpy' : 'sicpjs';
$makeindex = "makeindex -l $sicp_base.idx";
