on:
  push:
    branches:
      - master

# kill any builds still running from older commits
concurrency:
  group: deploy-pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install pandoc
        run: |
          URL="https://github.com/jgm/pandoc/releases/download/2.14.0.1/pandoc-2.14.0.1-1-amd64.deb"
          wget $URL -O /tmp/pandoc.deb
          sudo dpkg -i /tmp/pandoc.deb
          # The above script adapted from https://gist.github.com/rossant/8b751a15d71d6d9403a8
      - name: Install TeX Live and Inkscape
        run: |
          sudo apt-get update -y
          sudo apt-get install -y texlive texlive-fonts-extra latexmk
      - name: Fetch Yarn dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: |
          set -euxo pipefail
          yarn run pdf || (cat latex_pdf/sicpjs.log && false)
          yarn run split
          yarn run js
          yarn run json
      - name: Package
        run: |
          yarn run prepare
          find docs_out -name .gitignore -delete -print
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_out
          cname: sicp.sourceacademy.org
          force_orphan: true
