on:
  workflow_dispatch:
  worflow_call:

concurrency:
  group: translate-everything
  cancel-in-progress: true

jobs:
  translate-everything:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: cd
        run: |
          cd i18n
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Fetch Yarn Dependencies
        run: |
          yarn install
      - name: Create .env
        run: |
          touch .env
          echo API_MODEL=gpt-4.1-nano >> .env
          echo API_KEY=${{ secrets.OPENAI_KEY }} >> .env
          # echo API_KEY=${{ secrets.OPENAI_KEY2 }} >> .env
          echo MAX_LEN=5000 >> .env
          echo MAX_TRANSLATION_NO=10 >> .env
          echo CONTEXT=3 >> .env
          echo TOKEN_WARNING=7000 >> .env
      - name: Run Translation
        run: |
          npx tsx index.ts
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./translation_output
          force_orphan: false # leave the possiblity for direct modification on translated xmls
